version: '3'
services:
  node:
    image: node:15.11.0-alpine3.10
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - mongo
      - redis
    command: npm start

  mongo:
    image: "mvertes/alpine-mongo"

  redis:
    image: "redis:6.2.1-alpine"
