version: '3'
services:
    node:
        image: node:20-alpine3.16
        expose:
            - "3000"
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        working_dir: /app
        stdin_open: true
        tty: true
        depends_on:
            - rabbitmq
        command: npm start
    rabbitmq:
        image: rabbitmq:3.11.16-alpine
